"use strict";
exports.__esModule = true;
// let a = "Welcome Back";
// console.log(a);
var x = 10;
var y = 20;
// let x = 40;
var a = "hello";
var a = "world";
var b = "hi";
var isBigeneer = false;
var total = 1;
var name = "Taha Ansari";
var sentence = "My name is ".concat(name, " \nand i am new to typescript");
// total = true;
var n = null;
var u = undefined;
var newTotal = null;
